Party-Time-Job/Party-Time-Job

public/check.svg
public/confirm.svg
src/app/globals.css
src/shared/ui/Dialog/Dialog.tsx
src/shared/ui/Dialog/type.ts
src/shared/ui/Dialog/ui/CheckDialogUi.tsx
src/shared/ui/Dialog/ui/ConfirmDialogUi.tsx
src/shared/ui/Dialog/ui/DialogContainer.tsx
src/shared/ui/Toast/Toast.tsx
src/shared/ui/Toast/ui/ShowToast.tsx
src/shared/ui/Toast/ui/ToastUi.tsx
src/widgets/api/updateInformation.ts

- 토스트 및 다이얼로그 구현
- 프로필 상세 페이지에서 토스트 또는 다이얼로그 사용하려고 공통 컴포넌트 제작했습니다. 기능 다 구현하신 후에 혹시 필요하시면 활용하시면 될 것 같습니다.
- 제가 아직도 tailwind가 어려운 것 같네요. 혹시 tailwind로 animation효과(정확히는 fade-in/out) 구현을 어떻게 할 수 있는지 알 수 있을까요ㅜㅜ? 그리고 조건식으로 tailwind 스타일을 줄 때 기존처럼 작성하면 되는지도 알려주시면 감사합니다~!
- closed: #56

[공통 컴포넌트] 추가 기능을 위한 토스트 및 다이얼로그 공통 컴포넌트 구현

---

next.config.mjs
src/app/search/page.tsx
src/entities/Notice/NoticeDetail.tsx
src/entities/Notice/NoticeList.tsx
src/entities/Notice/utils/getSavedNotice.ts
src/entities/Notice/utils/saveSeenNotice.ts
src/entities/Post/DetailPost.tsx
src/entities/Post/types.ts
src/pages/NoticeDetailPage/NoticeDetailPage.tsx
src/pages/NoticePage/NoticePage.tsx
src/pages/searchPage/SearchPage.tsx
src/pages/searchPage/getSearchList.ts
src/shared/api/RequestMethod.ts
src/widgets/Footer/ui/FooterIcon.tsx
src/widgets/Header/ui/HeaderInput.tsx

- 최근 본 공고(6개) 기능
- 공고 검색 기능 구현
- 가게와 각 가게의 공고를 2팀 API 이용해서 3개 생성했습니다.
- 최근 본 공고 기능은 sessionStorage 를 이용했습니다.
- 공고 신청, 취소 기능은 03.18(월) 까지 완성하도록 하겠습니다
- closed: #13

최근 본 공고 기능, 공고 검색 기능 구현

---

public/modal-alert.svg
public/modal-check.svg
src/app/search/page.tsx
src/entities/Notice/NoticeDetail.tsx
src/entities/Notice/utils/saveSeenNotice.ts
src/entities/Post/DetailPost.tsx
src/entities/Post/types.ts
src/features/Modal/Modal.tsx
src/pages/NoticeDetailPage/NoticeDetailPage.tsx
src/pages/NoticeDetailPage/utils/getUserToken.ts
src/shared/ui/Logo.tsx

- 공고 지원 기능, 공고 취소 기능
- 각 상황의 모달 ui
- 코드가 많이 더러워서 리팩터링을 해야할듯 싶습니다
- 남은 기능은
-  페이지네이션 적용
- 공고 정렬 기능 정렬된 데이터 api로 불러오기로 수정, 디자인 수정 이렇게 남은 것 같습니다. 빨리할게유
- closed: #12

공고 지원, 취소 기능, 각 상황 모달 구현

---

src/app/profile/error.tsx
src/app/profile/page.tsx
src/features/LogIn/Types.ts
src/pages/LogInPage/LogInPage.tsx
src/widgets/NoProfile/NoProfileRegister.tsx
src/widgets/RegisterModal/RegisterModal.tsx
src/widgets/api/updateInformation.ts

- setCookie 사용해 토큰값과 유저id 저장
- 로그인 페이지에 로그인 후 토큰 값을 쿠키에 저장할 수 있게 setCookie를 사용했습니다.('token')
- 유저id도 전역 상태로 관리할 수 있게 우선 만들어보았습니다.('userid') TokenResponse에 필요한 타입 재정의하였습니다.
- 기본적으로 요청 전에 token을 getCookie를 통해 가져오게 해놓아서 이 부분 참고해서 만드셔도 좋을 것 같습니다.
- 아직 저도 PUT 메서드도 잘 되는지 확인을 못해서 같이 작업하시면서 수정할 부분 같이 수정해도 좋을 것 같습니다!!
- closed: #77

[일반회원 페이지] setCookie를 통해 토큰 값 쿠키에 저장

---

next.config.mjs
src/app/store/notice-detail/[shopId]/[noticeId]/page.tsx
src/entities/Employer/EmployerNoticeDetail.tsx
src/entities/Post/EmployerDetailPost.tsx
src/features/AcceptModal/AcceptModal.tsx
src/features/RejectModal/RejectModal.tsx
src/pages/EmployerPage/EmployerNoticeDetailPage.tsx
src/shared/ui/Table/Table.tsx
src/shared/ui/Table/type.ts

- 사장페이지 공고 상세 페이지 구현
- 시열님 사용하신 공용 모달은 더이상 범용성을 늘리기가 어려워서 따로 모달 만들어서 사용했습니다.
- ui 부분은 어차피 리모델링 해야하기 때문에 크게 공들이지 않았습니다!
- 데이터 이용하는 부분은 쿠키 사용하려고 했는데, CORS 에러가 계속 나서 결국은 포기하고 로컬 스토리지로 사용했습니다. 방식은 시열님과 동일합니다. 쿠키 사용하려는 과정에서 recoil을 사용하려고 했는데, 이것 때문에 에러가 생기는 것 같기도 합니다.
- 재명님이 만들어 놓으신 StoreTable 컴포넌트 사용했는데요, <img width="638" alt="image" src="https://github.com/Party-Time-Job/Party-Time-Job/assets/150772344/6c30e2a0-8c52-4f06-903c-26f2cbb26e9c"> 이 부분이 계속 Internal React Error가 발생해서 일단은 지웠습니다. 해당 부분 없어도 되는 코드인지, 그리고 무슨 목적으로 코드 작성하셨는지 팀미팅 때 간단하게 설명 부탁드릴게요!
- 시열님이 작성하신 코드와 많이 겹치기도 하고, 난이도 있는 페이지가 아니라서 JsDoc은 따로 작성하지 않았습니다. 혹시라도 여쭤보고 싶거나 배우고 싶으신 부분 있으시면 1:1 강의 해드리겠습니다!!
- closed: #76

사장페이지 공고 상세 페이지 구현

---

src/app/layout.tsx
src/app/profile/page.tsx
src/shared/ui/Pagination/Pagination.tsx
src/shared/ui/Table/Table.tsx
src/widgets/ProfileContainer/ui/ProfileContainerUi.tsx

- 프로필 창 연락처 수정
- 간단한 수정했습니다. 승인해주시고 바로 사용해주시면 됩니다!!

[일반회원 페이지] 간단한 수정

---

src/shared/utils/formatTime.ts

- 잘못 불러와지는 일자 수정
- 프로필 내 일자가 잘못 받아와지고 있었네요. 시열님 덕분에 알아챘습니다.. 감사합니다!!

[일반회원 페이지] 프로필 페이지 테이블 내 일자 수정

---

src/app/store/details/[id]/page.tsx
src/entities/Employer/EmployerNoticeList.tsx
src/entities/Employer/EmployerPost.tsx
src/entities/Notice/NoticeList.tsx
src/features/Create-Recruitment/CreateRecruitment.tsx
src/pages/EmployerPage/DetailsPage.tsx

- 기존 NoticeList & Post Component를 활용해 따로 파일을 만들어 모집 공고 등록 기능을 구현하였습니다
- 이후 리팩토링후 PR 올리겠습니다

[EmployerPage] 모집 공고 등록 기능 구현

---

.github/workflows/autoDeploy.yml

-  autoDeploy.yml 파일 생성
조직에서 관리하는 레포는 vercel에 유료로 배포를 해야해서 
우회 방법으로 조직 레포 -> 제 개인 레포 -> vercel에 반영 
위 과정을 자동으로 해주는 작업을 진행했습니다.

auto deploy를 위한 github action 파일 생성

---

build.sh

- build.sh 파일 생성
- 이제 진짜 마지막 단계입니당
- [참고 블로그](https://velog.io/@rmaomina/organization-vercel-hobby-deploy)

auto deploy를 위한 자동화 파일 생성

---

src/app/shop/details/page.tsx
src/app/shop/registration/shop-info/[shopId]/page.tsx
src/features/Create-Shop/CreateShop.tsx
src/page/EmployerPage/DetailsPage.tsx

- 라우팅 경로가 잘못돼 가게 등록전 등록하기 버튼으로 페이지 이동시 404 페이지 발생하는 오류 수정 후 PR 올립니다
-
- closed: #

[Fix] Employer - shop - details 페이지 버그 수정

---

.github/workflows/autoDeploy.yml
build 2.sh

auto push deploy

---

src/app/detail/[shopId]/[noticeId]/layout.tsx
src/app/notice/layout.tsx
src/entities/Employer/EmployerNoticeDetail.tsx
src/entities/Notice/CustomNotice.tsx
src/entities/Notice/NoticeDetail.tsx
src/entities/Notice/NoticeList.tsx
src/shared/ui/Loader.tsx

- 시열님 페이지 로딩 상태 변경
- Hydration 불일치 오류가 있긴한데 동작은 잘 되고 있습니다.

[세팅] 로딩 상태 변경

---

src/entities/Notice/NoticeList.tsx
src/entities/Notice/NoticeListLoading.tsx

[세팅] 로딩 상태 수정

---

src/app/globals.css
src/features/AcceptModal/AcceptModal.tsx
src/features/RejectModal/RejectModal.tsx
src/page/LandingPage/LandingPage.tsx
src/shared/NotificationModal/NotificationModal.tsx
src/shared/ui/Logo.tsx
src/widgets/Header/Header.tsx
src/widgets/Header/ui/HeaderButton.tsx
src/widgets/Header/ui/NotificationIcon.tsx

- 헤더 디자인 개선
- 헤더 알림 아이콘 버그 픽스
- 헤더 알림 로직 버그 픽스에 따른 로직 변경
- 내 가게 모달창 디자인 수정
- 현재 내 가게 페이지 공고 지원 목록에서 승인이나 거부를 누르면, 처음 한 번만 정상적으로 적용되고 그 이후의 지원들은 적용되지 않습니다.
- closed: #140

기타 버그 픽스 및 디자인 수정

---

src/shared/ui/Loader.tsx

Style: 로딩 스타일 변경

---

src/features/Create-Shop/CreateShop.tsx
src/page/EmployerPage/DetailsPage.tsx

1.  presignedURL을 생성할때는 file.name을 보내주고 
2.  aws s3 이미지 Post를 보낼때는 1번 에서 생성된 presignedURL과  file 을 보내줍니다 
3. 이후 aws s3 이미지 bucket에서 key를 조회해 get 해옵니다 ! 
-
- closed: #

[EmployerPage] 이미지 등록 오류 수정

---

src/features/AccountPageLogoLink/AccountPageLogoLink.tsx

- 공고리스트 페이지 -> 랜딩페이지
-
- closed: #159

로그인, 회원가입 페이지 로고 이동 링크 수정

---

src/features/Create-Shop/CreateShop.tsx

- 인풋 숨기기 적용 안 돼서 적용했습니다 윤성님 ^^ 내일 어프로브 부탁드립니다!
-
- closed: #

가게 등록 페이지 이미지 추가하기 인풋 숨기기

---

src/entities/Notice/hooks/useCustomNotice.ts
src/entities/Notice/hooks/useCustomNoticeScroll.ts

fix: console.log 제거 및 로그인 한 유저 맞춤 공고 갯수 수정

---

src/shared/ui/Loader.tsx

[세팅] 새로고침 시 로딩 상태 구현 수정

---

src/features/Create-Shop/CreateShop.tsx

- [EployerPage] 이미지 업로드 수정
-
- closed: #

[EployerPage] 이미지 업로드 수정

---

src/entities/Post/Post.tsx

fix: Post 화살표 음수일때 아래로 향하게

---

src/entities/Notice/NoticeList.tsx
src/entities/Notice/Pagination.tsx
src/entities/Notice/utils/getNoticeList.ts

fix: 필터 페이지네이션 오류 수정

---

src/app/shop/details/[shopId]/loading.tsx
src/app/shop/registration/recruitment/[id]/loading.tsx
src/app/shop/registration/shop-info/[shopId]/loading.tsx

[refac] employerPage ssr loadingSpinner 적용
